### ISSUE TITLE
Now there's a new bug (LoadingSavedFrequenciesDefaultsTo1)

### ISSUE THREAD

**Issue by SirHacksABunch** [Wizzy987/CCT211#25]
When saving a budget, the frequencies are saved correctly however when loading the saved .csv fie, all the frequencies for all expenses/incomes default to 1

**Comment by SirHacksABunch** [comment]
Further testing shows that inheritance is not the cause of the .csv files loading improperly although that code block I copy and pasted earlier in the chat probably contains the bug

Very small chance the bug of same timeframe expense/income registering all at once at the start of each timeframe multiple is connected to improper expense/income frequency loading (the latter would be a byproduct of the former). I highly doubt this though you never know

**Comment by XionideInk** [comment]
1. it's specifically happening here line (192, 193 for me):
self.expenses[index].timeframeData.set(self.account.expenses[index].timeframe)
self.expenses[index].frequencyData.set(self.account.expenses[index].frequency)

2. it loads the data properly, but suddenly changes. so the data load is correct, but somehow sets incorrectly. ie the file can have a frequency of 3. it'll load 3 into the account. but it'll put 1 in the entry box

3. self.frequencyData.set(1)
this is in expense__init__ and sets the entry to 1. however, removing this line defaults the entry to 0

**Comment by SirHacksABunch** [comment]
Fixed: Jose figured out it was a simple exchange in place of line 192 and line 193. It's always the little things
