### ISSUE TITLE
New Bug: Creating graph with timeframe matching expense/income timeframe causes addition of all frequencies at the start of the timeframe

### ISSUE THREAD

**Issue by SirHacksABunch** [Wizzy987/CCT211#26]
Adding an expense/income as a timeframe and wanting a graph to output the expense/income in the same form of timeframe (ex: month or year) or any multiple of that timeframe causes **the expense/income to add right at the beginning of the time frame, rather than dispersing evenly amongst the x-axis**

Ex: _$4000 at the start of a month_ **rather than** the graph _displaying $2000 during day 15 and day 30_

**Comment by randsco** [comment]
This bug has been addressed in GraphTimeframeFix. This has not been merged to dev yet because some more features will be implemented on this branch.
